name: Docker Image Grype scan

on:
  push:
    branches: [main]
    tags:
      - '*'
  workflow_dispatch:

jobs:
  docker:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6.18.0
        with:
          push: false
          load: true
          tags: localbuild/testimage:latest
      -
        name: Scan image
        uses: anchore/scan-action@v6.3.0
        id: scan
        with:
          add-cpes-if-none: true
          fail-build: false
          image: localbuild/testimage:latest
      -
        name: Upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v3.29.1
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}